package org.tnsif.repository;
//program to demonstrate on the CURD operation.
import java.sql.PreparedStatement;

import java.sql.ResultSet;

import org.tnsif.entities.Student;
import java.sql.Statement;

public interface StudentRepo {
	/*The object used for executing a static
	 * SQL statement and returning the results it produces 
	 */
	
	Statement makeStatement ();
	PreparedStatement createPrepareStatement(String query);
	
	public int addQuery(String query,Student student);
	public int updateQuery(String query,Student student);
	public int deleteQuery(String query);
	
	/*
	 * A table of data representing a database result set,
	 *  which is usually generated by executing a statement
	 *   that queries the database.
	 */
	
	public ResultSet retrieveQuery(String query);

	
	
	

}
